run:
  timeout: 5m
  skip-dirs-use-default: true
  skip-files-use-default: true
  issues-exit-code: 1

linters:
  disable:
    - goanalysis_metalinter
  enable:
    - errcheck
    - govet
    - gofmt
    - unused
    - staticcheck
    - gocritic

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "should have comment"                       # Не ругается на отсутствие комментариев
    - "error return value not checked"            # Не обязывает проверять все ошибки
    - "var .+ should be .*"                       # Не заставляет менять названия переменных

linters-settings:
  gofmt:
    simplify: true                                # Упрощает выражения (if x == true → if x)
