// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/delivery/v1/delivery.proto

package deliveryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сущность доставки
type Delivery struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId               int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId            int32                  `protobuf:"varint,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CourierId             int32                  `protobuf:"varint,4,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	Status                string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Priority              string                 `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`
	DeliveryAddress       string                 `protobuf:"bytes,7,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	EstimatedDeliveryTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=estimated_delivery_time,json=estimatedDeliveryTime,proto3" json:"estimated_delivery_time,omitempty"`
	DeliveredAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_api_delivery_v1_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_api_delivery_v1_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_api_delivery_v1_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *Delivery) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Delivery) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Delivery) GetCustomerId() int32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *Delivery) GetCourierId() int32 {
	if x != nil {
		return x.CourierId
	}
	return 0
}

func (x *Delivery) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Delivery) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Delivery) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *Delivery) GetEstimatedDeliveryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedDeliveryTime
	}
	return nil
}

func (x *Delivery) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

func (x *Delivery) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Delivery) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryRequest) Reset() {
	*x = GetDeliveryRequest{}
	mi := &file_api_delivery_v1_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryRequest) ProtoMessage() {}

func (x *GetDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_delivery_v1_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_api_delivery_v1_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeliveryRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *Delivery              `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryResponse) Reset() {
	*x = GetDeliveryResponse{}
	mi := &file_api_delivery_v1_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryResponse) ProtoMessage() {}

func (x *GetDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_delivery_v1_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_api_delivery_v1_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeliveryResponse) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_api_delivery_v1_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_delivery_v1_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_delivery_v1_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStatusRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AssignCourierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CourierId     int32                  `protobuf:"varint,2,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignCourierRequest) Reset() {
	*x = AssignCourierRequest{}
	mi := &file_api_delivery_v1_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignCourierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignCourierRequest) ProtoMessage() {}

func (x *AssignCourierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_delivery_v1_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignCourierRequest.ProtoReflect.Descriptor instead.
func (*AssignCourierRequest) Descriptor() ([]byte, []int) {
	return file_api_delivery_v1_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *AssignCourierRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AssignCourierRequest) GetCourierId() int32 {
	if x != nil {
		return x.CourierId
	}
	return 0
}

type MarkAsDeliveredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeliveredAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsDeliveredRequest) Reset() {
	*x = MarkAsDeliveredRequest{}
	mi := &file_api_delivery_v1_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsDeliveredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsDeliveredRequest) ProtoMessage() {}

func (x *MarkAsDeliveredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_delivery_v1_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsDeliveredRequest.ProtoReflect.Descriptor instead.
func (*MarkAsDeliveredRequest) Descriptor() ([]byte, []int) {
	return file_api_delivery_v1_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *MarkAsDeliveredRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MarkAsDeliveredRequest) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_delivery_v1_delivery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_delivery_v1_delivery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_delivery_v1_delivery_proto_rawDescGZIP(), []int{6}
}

var File_api_delivery_v1_delivery_proto protoreflect.FileDescriptor

const file_api_delivery_v1_delivery_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/delivery/v1/delivery.proto\x12\vdelivery.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\x03\n" +
	"\bDelivery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\x05R\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x04 \x01(\x05R\tcourierId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\x12)\n" +
	"\x10delivery_address\x18\a \x01(\tR\x0fdeliveryAddress\x12R\n" +
	"\x17estimated_delivery_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x15estimatedDeliveryTime\x12=\n" +
	"\fdelivered_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"$\n" +
	"\x12GetDeliveryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"H\n" +
	"\x13GetDeliveryResponse\x121\n" +
	"\bdelivery\x18\x01 \x01(\v2\x15.delivery.v1.DeliveryR\bdelivery\"=\n" +
	"\x13UpdateStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"E\n" +
	"\x14AssignCourierRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x02 \x01(\x05R\tcourierId\"g\n" +
	"\x16MarkAsDeliveredRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12=\n" +
	"\fdelivered_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\"\a\n" +
	"\x05Empty2\xbd\x02\n" +
	"\x0fDeliveryService\x12P\n" +
	"\vGetDelivery\x12\x1f.delivery.v1.GetDeliveryRequest\x1a .delivery.v1.GetDeliveryResponse\x12D\n" +
	"\fUpdateStatus\x12 .delivery.v1.UpdateStatusRequest\x1a\x12.delivery.v1.Empty\x12F\n" +
	"\rAssignCourier\x12!.delivery.v1.AssignCourierRequest\x1a\x12.delivery.v1.Empty\x12J\n" +
	"\x0fMarkAsDelivered\x12#.delivery.v1.MarkAsDeliveredRequest\x1a\x12.delivery.v1.EmptyB\x1cZ\x1aapi/delivery/v1;deliveryv1b\x06proto3"

var (
	file_api_delivery_v1_delivery_proto_rawDescOnce sync.Once
	file_api_delivery_v1_delivery_proto_rawDescData []byte
)

func file_api_delivery_v1_delivery_proto_rawDescGZIP() []byte {
	file_api_delivery_v1_delivery_proto_rawDescOnce.Do(func() {
		file_api_delivery_v1_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_delivery_v1_delivery_proto_rawDesc), len(file_api_delivery_v1_delivery_proto_rawDesc)))
	})
	return file_api_delivery_v1_delivery_proto_rawDescData
}

var file_api_delivery_v1_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_delivery_v1_delivery_proto_goTypes = []any{
	(*Delivery)(nil),               // 0: delivery.v1.Delivery
	(*GetDeliveryRequest)(nil),     // 1: delivery.v1.GetDeliveryRequest
	(*GetDeliveryResponse)(nil),    // 2: delivery.v1.GetDeliveryResponse
	(*UpdateStatusRequest)(nil),    // 3: delivery.v1.UpdateStatusRequest
	(*AssignCourierRequest)(nil),   // 4: delivery.v1.AssignCourierRequest
	(*MarkAsDeliveredRequest)(nil), // 5: delivery.v1.MarkAsDeliveredRequest
	(*Empty)(nil),                  // 6: delivery.v1.Empty
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_api_delivery_v1_delivery_proto_depIdxs = []int32{
	7,  // 0: delivery.v1.Delivery.estimated_delivery_time:type_name -> google.protobuf.Timestamp
	7,  // 1: delivery.v1.Delivery.delivered_at:type_name -> google.protobuf.Timestamp
	7,  // 2: delivery.v1.Delivery.created_at:type_name -> google.protobuf.Timestamp
	7,  // 3: delivery.v1.Delivery.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: delivery.v1.GetDeliveryResponse.delivery:type_name -> delivery.v1.Delivery
	7,  // 5: delivery.v1.MarkAsDeliveredRequest.delivered_at:type_name -> google.protobuf.Timestamp
	1,  // 6: delivery.v1.DeliveryService.GetDelivery:input_type -> delivery.v1.GetDeliveryRequest
	3,  // 7: delivery.v1.DeliveryService.UpdateStatus:input_type -> delivery.v1.UpdateStatusRequest
	4,  // 8: delivery.v1.DeliveryService.AssignCourier:input_type -> delivery.v1.AssignCourierRequest
	5,  // 9: delivery.v1.DeliveryService.MarkAsDelivered:input_type -> delivery.v1.MarkAsDeliveredRequest
	2,  // 10: delivery.v1.DeliveryService.GetDelivery:output_type -> delivery.v1.GetDeliveryResponse
	6,  // 11: delivery.v1.DeliveryService.UpdateStatus:output_type -> delivery.v1.Empty
	6,  // 12: delivery.v1.DeliveryService.AssignCourier:output_type -> delivery.v1.Empty
	6,  // 13: delivery.v1.DeliveryService.MarkAsDelivered:output_type -> delivery.v1.Empty
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_delivery_v1_delivery_proto_init() }
func file_api_delivery_v1_delivery_proto_init() {
	if File_api_delivery_v1_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_delivery_v1_delivery_proto_rawDesc), len(file_api_delivery_v1_delivery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_delivery_v1_delivery_proto_goTypes,
		DependencyIndexes: file_api_delivery_v1_delivery_proto_depIdxs,
		MessageInfos:      file_api_delivery_v1_delivery_proto_msgTypes,
	}.Build()
	File_api_delivery_v1_delivery_proto = out.File
	file_api_delivery_v1_delivery_proto_goTypes = nil
	file_api_delivery_v1_delivery_proto_depIdxs = nil
}
